Gemspec/DuplicatedAssignment:
  Enabled: false
Gemspec/RequiredRubyVersion:
  Enabled: false

Layout/AlignArguments:
  Enabled: false
Layout/AlignHash:
    Enabled: false
Layout/AlignParameters:
  Enabled: false
Layout/EndAlignment:
  EnforcedStyleAlignWith: "variable"
Layout/IndentFirstHashElement:
  Enabled: false
Layout/IndentHeredoc:
    Enabled: false

Lint/NestedMethodDefinition:
  Enabled: false
Lint/RescueException:
  Enabled: false

Metrics/AbcSize:
  Enabled: false
Metrics/BlockLength:
  Enabled: false
Metrics/ClassLength:
  Enabled: false
Metrics/LineLength:
  Max: 100
Metrics/MethodLength:
  Enabled: false
Metrics/ParameterLists:
  Max: 6

Naming/UncommunicativeMethodParamName:
  Enabled: false

Style/AndOr:
  Enabled: false
Style/CaseEquality:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/DoubleNegation:
  Enabled: false
Style/EachWithObject:
  Enabled: false
Style/GuardClause:
  Enabled: false
Style/NonNilCheck:
  Enabled: false
Style/RegexpLiteral:
  Enabled: false
Style/SignalException:
  Enabled: false
Style/SpecialGlobalVars:
  Enabled: false
Style/StringLiterals:
  EnforcedStyle: "double_quotes"
Style/TrailingCommaInArguments:
  Enabled: false
Style/TrailingCommaInArrayLiteral:
  Enabled: false
Style/TrailingCommaInHashLiteral:
  Enabled: false
Style/TrivialAccessors:
  Enabled: false
