language: "ruby"
sudo: false
cache: "bundler"
env:
  global:
    "CC_TEST_REPORTER_ID=505b5e2a819ce1ad685558da73ff1dedc6bac6aaa04ab593a02ac48a5303d4fd"
matrix:
  include:
    - rvm: "2.6"
    - rvm: "jruby-9"
      env: "JRUBY_OPTS=--debug"
  allow_failures:
    - rvm: "jruby-9"
      env: "JRUBY_OPTS=--debug"
  fast_finish: true
script: "bundle exec rake"
before_install:
  - "gem update --system"
  - "gem update bundler"
before_script:
  - "curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter"
  - "chmod +x ./cc-test-reporter"
  - "./cc-test-reporter before-build"
after_script:
  - "./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT"
services:
  - "redis-server"
if: "type != push OR (tag IS blank AND branch = master)"
notifications:
  email: false
